# Generated by Django 3.2 on 2022-10-06 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eithers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.CharField(choices=[('Blue', 'issue_a'), ('Red', 'issue_b')], default='Blue', max_length=4)),
                ('content', models.CharField(max_length=30)),
                ('either', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eithers.either')),
            ],
        ),
    ]
